// Token tek doğru kaynağı: packages/ui/src/tokens/
// Bu script tokens'tan apps/web/app/globals.css içindeki @theme bloğunu otomatik üretir.
// predev + prebuild hook'larıyla otomatik koşar; manuel: pnpm theme:sync
//
// MVP politikası: otomatik dark mode YOK. Sadece light tema üretilir.
// `prefers-color-scheme: dark` bloğu bilinçli olarak emit edilmez —
// `colorsDark` paleti ileride manuel `data-theme="dark"` opt-in için saklanıyor.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { colors, cssTheme } from "../packages/ui/src/tokens/colors";
import { radius } from "../packages/ui/src/tokens/radius";
import { shadow } from "../packages/ui/src/tokens/shadow";
import { fontFamily } from "../packages/ui/src/tokens/typography";
import { layout } from "../packages/ui/src/tokens/spacing";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const globalsPath = resolve(projectRoot, "apps/web/app/globals.css");

const BEGIN_MARKER = "/* THEME-SYNC:BEGIN — DO NOT EDIT — generated by scripts/sync-theme.ts */";
const END_MARKER = "/* THEME-SYNC:END */";

function radiusLines(): string[] {
  return Object.entries(radius)
    .filter(([key]) => key !== "DEFAULT")
    .map(([key, value]) => `  --radius-${key}: ${value};`);
}

function shadowLines(): string[] {
  return Object.entries(shadow).map(([key, value]) => `  --shadow-${key}: ${value};`);
}

function fontLines(): string[] {
  return Object.entries(fontFamily).map(
    ([key, stack]) => `  --font-${key}: ${stack.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", ")};`,
  );
}

function containerLines(): string[] {
  return [`  --max-w-container: ${layout["container-max"]};`];
}

function buildLightBlock(): string {
  const lines = [
    "@theme {",
    "  /* ----- Colors (M3 semantic + brand alias + state) ----- */",
    ...cssTheme(colors.light),
    "",
    "  /* ----- Fonts ----- */",
    ...fontLines(),
    "",
    "  /* ----- Sharp corners (Industrial Precision) ----- */",
    ...radiusLines(),
    "",
    "  /* ----- Shadows (sadece modal/popover/pressed) ----- */",
    ...shadowLines(),
    "",
    "  /* ----- Layout ----- */",
    ...containerLines(),
    "}",
  ];
  return lines.join("\n");
}

function buildGeneratedBlock(): string {
  return [BEGIN_MARKER, buildLightBlock(), END_MARKER].join("\n");
}

function syncGlobalsCss(): void {
  const current = readFileSync(globalsPath, "utf8");
  const generated = buildGeneratedBlock();

  let next: string;

  const markerRegex = new RegExp(
    `${escapeRegex(BEGIN_MARKER)}[\\s\\S]*?${escapeRegex(END_MARKER)}`,
    "m",
  );

  if (markerRegex.test(current)) {
    next = current.replace(markerRegex, generated);
  } else {
    // İlk koşu: el yazısı @theme bloğunu marker'lı blokla değiştir.
    const themeRegex = /@theme\s*\{[\s\S]*?\n\}/m;
    if (themeRegex.test(current)) {
      next = current.replace(themeRegex, generated);
    } else {
      // @theme da yoksa: dosyanın sonuna ekle.
      next = `${current.trimEnd()}\n\n${generated}\n`;
    }
  }

  // Idempotency: aynı içerikse yazma.
  if (next === current) {
    console.log("theme:sync — no changes (already in sync)");
    return;
  }

  writeFileSync(globalsPath, next, "utf8");
  console.log(`theme:sync — wrote ${globalsPath}`);
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

syncGlobalsCss();
